#!/usr/bin/env python3
"""Convert source/footnotes.md into print/endnotes.typ (back matter).

- numbering follows the body's first-appearance order (source/hojoki.md)
- each endnote begins on a new page (#pagebreak between them)
- markdown -> Typst: *italic* -> #emph[], [text](url) -> text, NBSP before em-dash
- the «Джерела» (Sources) section becomes a Typst list on its own page
Run from the project root: python3 print/tools/build_endnotes.py
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
HOJOKI = (ROOT / "source/hojoki.md").read_text(encoding="utf-8")
FN = (ROOT / "source/footnotes.md").read_text(encoding="utf-8")

# 1) body order of markers (first appearance)
order = []
for m in re.finditer(r"\[\^([^\]]+)\]", HOJOKI):
    if "]:" in HOJOKI[m.start():m.start()+len(m.group(0))+1]:
        continue  # skip definition lines (none in hojoki.md, but be safe)
    if m.group(1) not in order:
        order.append(m.group(1))

# 2) drop the «Джерела» (sources) section — print/ebook omit it; only the web build keeps it
notes_text = re.split(r"(?m)^#\s+Джерела\s*$", FN)[0]

def collapse(s):
    return " ".join(s.split())

def render_lemma(inner):
    # a verse excerpt — keep source line breaks; blank line = stanza gap.
    stanzas = []
    for st in re.split(r"\n\s*\n", inner.strip()):
        lines = [ln.strip().replace(" —", "\\u{00A0}—") for ln in st.splitlines() if ln.strip()]
        if lines:
            stanzas.append(" \\\n".join(lines))   # verse line breaks within a stanza
    return "\n\n".join(stanzas)                     # blank line between stanzas

def convert_inline(text):  # markdown inline -> Typst, possibly spanning lines
    text = re.sub(r"\*\*(.+?)\*\*", lambda m: "#strong[" + collapse(m.group(1)) + "]", text, flags=re.DOTALL)
    text = re.sub(r"\*(.+?)\*",     lambda m: "#emph[" + collapse(m.group(1)) + "]",   text, flags=re.DOTALL)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)   # links -> text
    text = text.replace(" —", "\\u{00A0}—")                # NBSP before em-dash
    return text

def md_to_typ(block):
    # `---` on its own line = a deliberate page break inside a note; the text that
    # follows (a continuation, not a note start) is centered vertically on its page.
    lines = [l[4:] if l.startswith("    ") else l for l in block.splitlines()]
    text = convert_inline("\n".join(lines))
    before, after, split = [], [], False
    for p in re.split(r"\n\s*\n", text):
        plines = [x for x in p.splitlines() if x.strip()]
        if not plines:
            continue
        joined = " ".join(x.strip() for x in plines)
        if joined.strip() == "---":
            split = True
            continue
        if any(x.lstrip().startswith("-") for x in plines):   # bullet list — keep items separate
            item = "\n".join("- " + x.lstrip()[1:].strip() for x in plines)
        else:                                                  # prose — collapse to one line
            item = joined
        (after if split else before).append(item)
    if split:
        # continuation begins at the verse level: reserve the number's space (no number
        # printed) so the text starts where the lemma/verse would, not at the top.
        return ("\n\n".join(before)
                + "\n\n#pagebreak()\n#hide(text(weight: \"bold\", size: 12pt)[1.])\n#v(4.7mm)\n"
                + "\n\n".join(after))
    return "\n\n".join(before)

# 3) parse footnote definitions -> (lemma verse, prose body)
defs = {}
matches = list(re.finditer(r"(?m)^\[\^([^\]]+)\]:[ \t]?(.*)$", notes_text))
for i, m in enumerate(matches):
    end = matches[i + 1].start() if i + 1 < len(matches) else len(notes_text)
    block = m.group(2) + notes_text[m.end():end]  # m.end() sits just before the newline
    deindented = "\n".join(l[4:] if l.startswith("    ") else l
                           for l in block.splitlines()).strip("\n")
    q = re.match(r"\s*\*(.+?)\*", deindented, flags=re.DOTALL)  # leading *…* quote span
    if q:
        lemma = render_lemma(q.group(1))           # quote → verse (may be multi-stanza)
        body = md_to_typ(deindented[q.end():])     # rest → prose
    else:
        lemma, body = "", md_to_typ(deindented)
    defs[m.group(1)] = (lemma, body)

# 5) emit (no «Джерела» — print/ebook omit it)
out = ['// GENERATED by print/tools/build_endnotes.py — do not edit by hand.',
       '#import "template/layout.typ": *',
       '#import "template/typography.typ": *',
       '#import "template/components.typ": *', "",
       '#metadata("Примітки")<chap>',   # running-header marker for the section (markup mode: no [])
       '#section-heading("Примітки")', ""]
for n, marker in enumerate(order, start=1):
    lemma, body = defs.get(marker, ("", "*(missing: %s)*" % marker))
    if n > 1:
        out += ["#pagebreak()", ""]
    out += ["#endnote(%d)[" % n, lemma, "][", body, "]", ""]

(ROOT / "print/endnotes.typ").write_text("\n".join(out), encoding="utf-8")
print("endnotes.typ written;", len(order), "notes:", order)
