#!/usr/bin/env python3
"""Convert source/footnotes.md into print/endnotes.typ (back matter).

- numbering follows the body's first-appearance order (source/hojoki.md)
- each endnote begins on a new page (#pagebreak between them)
- markdown -> Typst: *italic* -> #emph[], [text](url) -> text, NBSP before em-dash
- the «Джерела» (Sources) section becomes a Typst list on its own page
Run from the project root: python3 print/tools/build_endnotes.py
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
HOJOKI = (ROOT / "source/hojoki.md").read_text(encoding="utf-8")
FN = (ROOT / "source/footnotes.md").read_text(encoding="utf-8")

# 1) body order of markers (first appearance)
order = []
for m in re.finditer(r"\[\^([^\]]+)\]", HOJOKI):
    if "]:" in HOJOKI[m.start():m.start()+len(m.group(0))+1]:
        continue  # skip definition lines (none in hojoki.md, but be safe)
    if m.group(1) not in order:
        order.append(m.group(1))

# 2) split off the «Джерела» (sources) section
parts = re.split(r"(?m)^#\s+Джерела\s*$", FN)
notes_text, sources_text = parts[0], (parts[1] if len(parts) > 1 else "")

def collapse(s):
    return " ".join(s.split())

def convert_inline(text):  # markdown inline -> Typst, possibly spanning lines
    text = re.sub(r"\*\*(.+?)\*\*", lambda m: "#strong[" + collapse(m.group(1)) + "]", text, flags=re.DOTALL)
    text = re.sub(r"\*(.+?)\*",     lambda m: "#emph[" + collapse(m.group(1)) + "]",   text, flags=re.DOTALL)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)   # links -> text
    text = text.replace(" —", "\\u{00A0}—")                # NBSP before em-dash
    return text

def md_to_typ(block):
    lines = [l[4:] if l.startswith("    ") else l for l in block.splitlines()]
    text = convert_inline("\n".join(lines))
    out = []
    for p in re.split(r"\n\s*\n", text):
        plines = [x for x in p.splitlines() if x.strip()]
        if not plines:
            continue
        if any(x.lstrip().startswith("-") for x in plines):   # bullet list — keep items separate
            out.append("\n".join("- " + x.lstrip()[1:].strip() for x in plines))
        else:                                                  # prose — collapse to one line
            out.append(" ".join(x.strip() for x in plines))
    return "\n\n".join(out)

# 3) parse footnote definitions
defs = {}
matches = list(re.finditer(r"(?m)^\[\^([^\]]+)\]:[ \t]?(.*)$", notes_text))
for i, m in enumerate(matches):
    end = matches[i + 1].start() if i + 1 < len(matches) else len(notes_text)
    block = m.group(2) + notes_text[m.end():end]  # m.end() sits just before the newline
    defs[m.group(1)] = md_to_typ(block)

# 5) emit
out = ['// GENERATED by print/tools/build_endnotes.py — do not edit by hand.',
       '#import "template/layout.typ": *',
       '#import "template/typography.typ": *',
       '#import "template/components.typ": *', "",
       '#fm-heading("Примітки")', ""]
for n, marker in enumerate(order, start=1):
    body = defs.get(marker, "*(missing: %s)*" % marker)
    if n > 1:
        out += ["#pagebreak()", ""]
    out += ["#endnote(%d)[" % n, body, "]", ""]

out += ["#pagebreak()", "", '#fm-heading("Джерела")', "",
        "#prose[", md_to_typ(sources_text), "]", ""]

(ROOT / "print/endnotes.typ").write_text("\n".join(out), encoding="utf-8")
print("endnotes.typ written;", len(order), "notes:", order)
